import { Button } from "@chakra-ui/react";
import Head from "next/head";
import api from "../store/api/api";
import { wrapper } from "../store/store";

export const getServerSideProps = wrapper.getServerSideProps((store) => async ({ req, res }) => {
  store.dispatch(api.endpoints.getApiAuthGetCurrentUser.initiate());
  store.dispatch(api.endpoints.getWeatherForecast.initiate());

  await Promise.all(api.util.getRunningOperationPromises());
  console.log(store.getState().api.queries);

  return {
    props: {},
  };
});

const Home = () => {
  const { data: user, isError, error } = api.useGetApiAuthGetCurrentUserQuery();
  const { data, isFetching, refetch } = api.useGetWeatherForecastQuery();

  const [logout] = api.usePostApiAuthLogoutMutation();
  const [login] = api.usePostApiAuthLogInMutation();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div> {isError ? JSON.stringify(error) : <h1>Welcome to .Net</h1>}</div>

        {user ? (
          <div>
            <p>Logged in: {user.email} </p>
            <p>Email Confirmed: {user.emailConfirmed ? "Yes" : "No"} </p>

            <Button onClick={() => logout()}>Logout</Button>
          </div>
        ) : (
          <p>
            No Logged in :{" "}
            <Button
              onClick={() =>
                login({
                  loginInput: {
                    username: "riyaadh.abr@gmail.com",
                    password: "Cat.00000",
                    rememberMe: true,
                  },
                })
              }
            >
              Login
            </Button>
          </p>
        )}
        <Button disabled={!user} onClick={refetch}>
          Refetch
        </Button>
        <p style={{ textAlign: "center" }}>{JSON.stringify(data)}</p>
      </main>
    </div>
  );
};

export default Home;
